window.PuneethPracticeSets = {
  "python-runtime": {
    quizId: "python-runtime-v1",
    phaseId: "00",
    topic: "Python runtime & package management",
    title: "Practice Lab · Reproducible Python environments",
    questions: [
      {id:"py-runtime-01",q:"A project works on your laptop but fails on a teammate’s machine with ModuleNotFoundError: requests. The teammate is using the same source code. What is the most direct engineering hypothesis to test first?",options:["The source code must contain a syntax error.","The two environments do not have the same installed dependency set or interpreter environment.","The operating system must be incapable of running Python.","The network connection must be the root cause."],answer:1,explanation:"ModuleNotFoundError means the active interpreter cannot import the module. With identical source, first compare the active interpreter and installed packages. Check python --version, python -c \"import sys; print(sys.executable)\", and python -m pip show requests."},
      {id:"py-runtime-02",q:"You create a virtual environment with python -m venv .venv. What problem does the virtual environment primarily solve?",options:["It prevents Python from executing files.","It guarantees identical behavior on every operating system.","It isolates project-installed packages from other project environments.","It automatically commits dependency versions to Git."],answer:2,explanation:"A virtual environment gives the project its own package installation context. This reduces cross-project dependency conflicts. It does not create a lock file or guarantee complete machine-level reproducibility."},
      {id:"py-runtime-03",q:"A project records requests==2.32.5. Why is the == constraint useful for reproducibility?",options:["It tells Python to ignore the package.","It allows any version newer than 2.32.5.","It requires that exact version to be selected, assuming it is available for the environment.","It converts the package into a standard-library module."],answer:2,explanation:"A dependency constraint defines the allowed version set. ==2.32.5 narrows that set to one version, reducing dependency drift. Complete reproducibility can still depend on the Python version, platform, transitive dependencies and other environment inputs.",latex:"AllowedVersions = {2.32.5}"},
      {id:"py-runtime-04",q:"You discover that pip belongs to a different Python installation than the python command used to run the project. Which command is the safest diagnostic habit?",options:["python -m pip --version","pip --guess-python","python --packages","pip use-current-interpreter"],answer:0,explanation:"python -m pip runs pip through the selected Python interpreter. Checking python -m pip --version therefore shows which pip installation is associated with that interpreter and avoids ambiguity from PATH resolution."},
      {id:"py-runtime-05",q:"A clean machine recreates the virtual environment and installs the recorded dependencies, but the application still behaves differently. Which conclusion is most technically responsible?",options:["Dependency files are useless and should be removed.","The problem is proven to be Python package versions.","Reproducibility also depends on runtime, OS libraries, environment variables, input data and external services.","The application must be rewritten in another language."],answer:2,explanation:"Recreating dependencies removes one source of drift, but the application can still depend on Python version, OS libraries, configuration, filesystem state, credentials, input data, network services or time-dependent systems. Reproduce the full relevant execution contract."}
    ]
  }
};