-- Puneeth AI Engineering — optional learner account setup
-- Run this in Supabase SQL Editor after creating a project.
-- NEVER expose the service_role key in the website.

create table if not exists public.user_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  progress jsonb not null default '{}'::jsonb,
  assessments jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_progress enable row level security;

create policy "Users can read their own progress"
on public.user_progress for select
using (auth.uid() = user_id);

create policy "Users can insert their own progress"
on public.user_progress for insert
with check (auth.uid() = user_id);

create policy "Users can update their own progress"
on public.user_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.user_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.user_events enable row level security;

create policy "Users can insert their own events"
on public.user_events for insert
with check (auth.uid() = user_id);

create policy "Users can read their own events"
on public.user_events for select
using (auth.uid() = user_id);

create index if not exists user_events_user_created_idx
on public.user_events(user_id, created_at desc);
